# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0003_auto_20151207_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='goodComment',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='check',
            name='badComment',
        ),
    ]
