# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0004_auto_20160127_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
    ]
